export const BOOKING_ERROR_CODES = {
  ALREADY_BOOKED: "ALREADY_BOOKED",
  CLASS_FULL: "CLASS_FULL",
  CLASS_INACTIVE: "CLASS_INACTIVE",
  CLASS_NOT_AVAILABLE_FOR_DATE: "CLASS_NOT_AVAILABLE_FOR_DATE",
  CLASS_TEMPLATE_NOT_FOUND: "CLASS_TEMPLATE_NOT_FOUND",
  LOCATION_NOT_FOUND: "LOCATION_NOT_FOUND",
  LOCATION_ID_REQUIRED: "LOCATION_ID_REQUIRED",
  INVALID_IDENTIFIER: "INVALID_IDENTIFIER",
  BOOKING_REFERENCE_NOT_FOUND: "BOOKING_REFERENCE_NOT_FOUND",
  BOOKING_TEMPORARILY_UNAVAILABLE: "BOOKING_TEMPORARILY_UNAVAILABLE",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  CANCELLATION_WINDOW_CLOSED: "CANCELLATION_WINDOW_CLOSED",
} as const;

export type BookingErrorCode =
  (typeof BOOKING_ERROR_CODES)[keyof typeof BOOKING_ERROR_CODES];
